import { Metadata } from 'next';  // For handling metadata in server-side layout
import ClientNavigation from './clientNavigation';  // Import the client-side navigation component

export const metadata = {
  title: 'Easely',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Render the client-side navigation component */}
        <ClientNavigation />
        
        {children}
      </body>
    </html>
  );
}