import Link from 'next/link'
import "./globals.css";

export const metadata = {
  title: 'Easely',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Link href="/">HOME</Link> 
        <Link href="/todo">TODO</Link>
        {children}
      </body>
    </html>
  )
}